<?php
session_start();
$name=$_POST['name'];
$brand=$_POST['brand'];
$series=$_POST['series'];
$color=$_POST['color'];
$price=$_POST['price'];
$category=$_POST['ctgry'];
$type=$_POST['type'];
$qty=$_POST['qty'];
$source="photo/phones/".basename($_FILES['image']['name']);
$image=$_FILES['image']['name'];
move_uploaded_file($_FILES['image']['tmp_name'],$source);
$_SESSION['name']=$name;
$_SESSION['brand']=$brand;
$_SESSION['series']=$series;
$_SESSION['color']=$color;
$_SESSION['category']=$category;
$_SESSION['type']=$type;
$_SESSION['price']=$price;
$_SESSION['qty']=$qty;
$_SESSION['image']=$image;
header("location:addfeature.php");
?>